spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/authuser
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: ead-authuser-service
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead.authuser: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost